# Generated by Django 5.1.6 on 2025-02-19 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_serviceorder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serviceorder',
            name='user',
        ),
    ]
