# Generated by Django 5.1.6 on 2025-02-19 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_alter_service_user_alter_serviceorder_service_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceorderreview',
            name='rating',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
